name: Acciojob Tests

on:
 push:
    branches: [ "main","master" ]

jobs:
  debug-print-spec:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout solution repo
        uses: actions/checkout@v3
        with:
          repository: acciojob/phoenix-airlines-solution
          path: solution-repo
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print spec file
        run: cat solution-repo/cypress/integration/tests/test.spec.js

  calling-acciojob-main-action:
    uses: acciojob/acciojob-tests-action/.github/workflows/main-action.yml@main
    secrets: inherit